# Generated by Django 5.1.7 on 2025-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ponto",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("pausado", "Pausado"),
                    ("finalizado", "Finalizado"),
                ],
                default="ativo",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ponto",
            name="carga_horaria",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ponto",
            name="entrada",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ponto",
            name="saida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
