# Generated by Django 5.1.7 on 2025-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_ponto_status_alter_ponto_carga_horaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ponto",
            name="tempo_pausado",
            field=models.DurationField(default=0),
        ),
        migrations.AddField(
            model_name="ponto",
            name="ultimo_pausa",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
