# Generated by Django 5.1.7 on 2025-04-02 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_ponto_tempo_pausado_ponto_ultimo_pausa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ponto",
            name="tempo_pausado",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
